# Site settings
title: Peeyush Agarwal blog
email: peeyushagarwal1994@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Musings of Peeyush Agarwal
baseurl: "/blog"
url: "http://apeeyush.github.io" # the base hostname & protocol for your site
twitter_username: AgrwaL_Peeyush
github_username:  apeeyush

# Build settings
markdown: kramdown
